In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('essays.csv', encoding="latin-1")

In [4]:
df.head(5)

AUTHID                                               TEXT cEXT  \
0  1997_504851.txt  Well, right now I just woke up from a mid-day ...    n   
1  1997_605191.txt  Well, here we go with the stream of consciousn...    n   
2  1997_687252.txt  An open keyboard and buttons to push. The thin...    n   
3  1997_568848.txt  I can't believe it!  It's really happening!  M...    y   
4  1997_688160.txt  Well, here I go with the good old stream of co...    y   

  cNEU cAGR cCON cOPN  
0    y    y    n    y  
1    n    y    n    n  
2    y    n    y    y  
3    n    y    y    n  
4    n    y    n    y

In [5]:
df= df.iloc[:,1:]

In [6]:
df.head()

TEXT cEXT cNEU cAGR cCON cOPN
0  Well, right now I just woke up from a mid-day ...    n    y    y    n    y
1  Well, here we go with the stream of consciousn...    n    n    y    n    n
2  An open keyboard and buttons to push. The thin...    n    y    n    y    y
3  I can't believe it!  It's really happening!  M...    y    n    y    y    n
4  Well, here I go with the good old stream of co...    y    n    y    n    y

In [7]:
df.isnull().sum()

TEXT    0
cEXT    0
cNEU    0
cAGR    0
cCON    0
cOPN    0
dtype: int64

In [8]:
df.shape

(2467, 6)

In [9]:
df.duplicated().sum()

0

In [10]:
#data is clean so we now rename columns to convinient names

In [11]:
df.rename(columns={'TEXT':'text','cEXT':'ext','cNEU':'neu','cAGR':'agr','cCON':'con','cOPN':'opn'},inplace=True)

In [12]:
df.head()

text ext neu agr con opn
0  Well, right now I just woke up from a mid-day ...   n   y   y   n   y
1  Well, here we go with the stream of consciousn...   n   n   y   n   n
2  An open keyboard and buttons to push. The thin...   n   y   n   y   y
3  I can't believe it!  It's really happening!  M...   y   n   y   y   n
4  Well, here I go with the good old stream of co...   y   n   y   n   y

In [13]:
#change to numerical values
df['ext'] = df['ext'].apply(lambda x: 1 if x == 'y' else 0)
df['neu'] = df['neu'].apply(lambda x: 1 if x == 'y' else 0)
df['agr'] = df['agr'].apply(lambda x: 1 if x == 'y' else 0)
df['con'] = df['con'].apply(lambda x: 1 if x == 'y' else 0)
df['opn'] = df['opn'].apply(lambda x: 1 if x == 'y' else 0)

In [14]:
df.head()

text  ext  neu  agr  con  opn
0  Well, right now I just woke up from a mid-day ...    0    1    1    0    1
1  Well, here we go with the stream of consciousn...    0    0    1    0    0
2  An open keyboard and buttons to push. The thin...    0    1    0    1    1
3  I can't believe it!  It's really happening!  M...    1    0    1    1    0
4  Well, here I go with the good old stream of co...    1    0    1    0    1

In [15]:
L=[]
for i in df['text'].values:
    L.extend(i.split())
L = list(set(L))

In [16]:
L


['believing',
 'AUSTRILIA',
 'Wedge,',
 'laught',
 'humility',
 'incorrect',
 'bs',
 'tthem',
 'represeintinng',
 'Alabama',
 "dorms'.",
 "wendy's",
 'weird?',
 'VOLLEYBALL',
 'california.',
 'mission!',
 'Wizard',
 "Matt's.",
 'vic,',
 'slacker.',
 'celebrities',
 'Britt',
 'short?',
 'skydiving',
 'cab?',
 'satrting',
 'seeing',
 'Soto',
 'mechanics.',
 'officially,',
 'Starcraft',
 'spots',
 'cursed',
 'taught',
 'good',
 'later?',
 'commenting',
 'Huge!',
 '"made',
 'Houston',
 'gods.',
 'tick.',
 'Mississippi',
 'fifths',
 'And.',
 '(I\x92m',
 'ROTC,',
 "comic's.",
 'exclusive',
 'kemo',
 'slimming',
 'whopping',
 'obssessive',
 'peck',
 'prob.',
 'sign.',
 'Peppers',
 'Americans.',
 'vie',
 'knees.',
 'tired',
 'driveway,',
 'banana.',
 'alowed',
 'BCIS.',
 'genie.',
 "didn't),",
 'activites',
 'topday',
 'guy"',
 'Virgin',
 'inevitable,',
 'moonlight',
 'subliminally.',
 'dozing',
 'kidding!',
 'headband',
 'HT',
 'venture',
 '9:30--I',
 'Kate.',
 'Hezbollah,',
 'miscommunicatio

In [17]:
#text preprocessing
#small letters
#remove special characters
#remove stopwords
#convert to vector


In [18]:
df['text'] = df['text'].apply( lambda x : x.lower())

In [19]:
df.head()

text  ext  neu  agr  con  opn
0  well, right now i just woke up from a mid-day ...    0    1    1    0    1
1  well, here we go with the stream of consciousn...    0    0    1    0    0
2  an open keyboard and buttons to push. the thin...    0    1    0    1    1
3  i can't believe it!  it's really happening!  m...    1    0    1    1    0
4  well, here i go with the good old stream of co...    1    0    1    0    1

In [20]:
def remove_special_chars(text):
    result = ""
    for i in text:
        if i.isalnum() or i ==' ':
            result = result + i
        else:
            result = result + ""
    return result.strip()

In [21]:
df['text'] = df['text'].apply(remove_special_chars)
df['text']

0       well right now i just woke up from a midday na...
1       well here we go with the stream of consciousne...
2       an open keyboard and buttons to push the thing...
3       i cant believe it  its really happening  my pu...
4       well here i go with the good old stream of con...
                              ...                        
2462    im home wanted to go to bed but remembered tha...
2463    stream of consiousnesssskdj how do you spell t...
2464    it is wednesday december 8th and a lot has bee...
2465    man this week has been hellish anyways now its...
2466    i have just gotten off the phone with brady im...
Name: text, Length: 2467, dtype: object

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
cv = CountVectorizer(stop_words='english',max_features = 87500)

In [24]:
X = cv.fit_transform(df['text']).toarray()
X.shape

(2467, 31828)

In [28]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [29]:
df.shape

(2467, 6)

In [30]:
ext = df['ext'].values.astype('int')
neu = df['neu'].values.astype('int')
agr = df['agr'].values.astype('int')
con = df['con'].values.astype('int')
opn = df['opn'].values.astype('int')

In [31]:
ext.shape

(2467,)

In [32]:
ext = df['ext']
neu=df['neu']
agr = df['agr']
con=df['con']
opn=df['opn']

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,ext_train,ext_test = train_test_split(X,ext,test_size=0.3)
X1_train,X1_test,neu_train,neu_test = train_test_split(X,neu,test_size=0.3)
X2_train,X2_test,agr_train,agr_test = train_test_split(X,agr,test_size=0.3)
X3_train,X3_test,con_train,con_test = train_test_split(X,con,test_size=0.3)
X4_train,X4_test,opn_train,opn_test = train_test_split(X,opn,test_size=0.3)

In [34]:
from sklearn.naive_bayes import MultinomialNB

In [35]:
eclf = MultinomialNB()
nclf = MultinomialNB()
aclf= MultinomialNB()
cclf = MultinomialNB()
oclf = MultinomialNB()

In [36]:
from sklearn.metrics import accuracy_score


In [37]:
eclf.fit(X_train,ext_train)
ext_pred = eclf.predict(X_test)

In [38]:
nclf.fit(X1_train,neu_train)
neu_pred = nclf.predict(X1_test)

In [39]:
aclf.fit(X2_train,agr_train)
agr_pred = aclf.predict(X2_test)

In [40]:
cclf.fit(X3_train,con_train)
con_pred = cclf.predict(X3_test)

In [41]:
oclf.fit(X4_train,opn_train)
opn_pred = oclf.predict(X4_test)

In [42]:
def find_accuracy(lst,pst):
  err=0
  sum=0
  for i in range(5):
    err+=(pst[i] - lst[i])**2
    sum+=pst[i]
  print(err/pst)


In [43]:
#4
text = "Many wishes of my life haven't been fulfilled. This makes me irritated. I feel like my life has been filled with diasspointments."
text = text.lower()
text = remove_special_chars(text)
val = cv.transform([text])
a = eclf.predict(val)
b = nclf.predict(val)
c = aclf.predict(val)
d = cclf.predict(val)
e = oclf.predict(val)

In [44]:
qualities = ['Extroversion','Neuroticism','Agreeableness','Conscientiousness','Openness']
values = [a,b,c,d,e]
for i in range(5):
  if(values[i][0]==0):
    print(qualities[i],': No')
  else:
    print(qualities[i],': Yes')

Extroversion : No
Neuroticism : Yes
Agreeableness : Yes
Conscientiousness : No
Openness : Yes


In [45]:
df.head(5)

text  ext  neu  agr  con  opn
0  well right now i just woke up from a midday na...    0    1    1    0    1
1  well here we go with the stream of consciousne...    0    0    1    0    0
2  an open keyboard and buttons to push the thing...    0    1    0    1    1
3  i cant believe it  its really happening  my pu...    1    0    1    1    0
4  well here i go with the good old stream of con...    1    0    1    0    1

In [46]:
accuracy_score(ext_test,ext_pred)

0.5425101214574899

In [47]:
accuracy_score(neu_test,neu_pred)

0.5519568151147098

In [48]:
accuracy_score(agr_test,agr_pred)

0.5654520917678812

In [49]:
accuracy_score(con_test,con_pred)

0.5519568151147098

In [50]:
accuracy_score(opn_test,opn_pred)

0.6423751686909581